name: Lusk
version: @version@
main: it.jakegblp.lusk.Lusk
website: https://github.com/JakeGBLP/Lusk
api-version: 1.13
depend:
  - Skript
softdepend:
  - SkBee # required due to an skbee issue
authors:
  - JakeGBLP