name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Install Gradle
        uses: sdkman/sdkman-action@main
        with:
          candidate: gradle
          version: 8.9
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lusk.jar
          path: build/libs/*.jar
  build_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Install Gradle
        uses: sdkman/sdkman-action@main
        with:
          candidate: gradle
          version: 8.9
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lusk_back.jar
          path: build/libs/*.jar
  test_dev_feature:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: dev/feature
          extra_plugins_directory: extra-plugins/
  test_2_10_0:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.10.0
          extra_plugins_directory: extra-plugins/
  test_2_9_5:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.9.5
          extra_plugins_directory: extra-plugins/
  test_2_8_7:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.8.7
          extra_plugins_directory: extra-plugins/
  test_2_7_3:
    runs-on: ubuntu-latest
    needs: [build_2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.7.3
          extra_plugins_directory: extra-plugins/
  test_2_6_4:
    runs-on: ubuntu-latest
    needs: [build_2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.6.4
          extra_plugins_directory: extra-plugins/
