name: Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Install Gradle
        uses: sdkman/sdkman-action@main
        with:
          candidate: gradle
          version: 8.6
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lusk.jar
          path: build/libs/*.jar
  test_dev_feature:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: dev/feature
          extra_plugins_directory: extra-plugins/
  test_2_9_5:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: 2.9.5
          extra_plugins_directory: extra-plugins/
