name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Install Gradle
        uses: sdkman/sdkman-action@main
        with:
          candidate: gradle
          version: 8.9
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile Minecraft Spigot (via BuildTools)
        uses: SpraxDev/Action-SpigotMC@v5.1.0
        with:
          versions: "1.16.5"
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lusk.jar
          path: build/libs/*.jar
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Install Gradle
        uses: sdkman/sdkman-action@main
        with:
          candidate: gradle
          version: 8.9
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile Minecraft Spigot (via BuildTools)
        uses: SpraxDev/Action-SpigotMC@v5.1.0
        with:
          version: '1.21.4'
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew testBuild
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lusk_test.jar
          path: build/libs/*.jar
  test_dev_feature:
    runs-on: ubuntu-latest
    needs: [test_build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: dev/feature
          extra_plugins_directory: extra-plugins/
  test_dev_patch:
    runs-on: ubuntu-latest
    needs: [test_build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/scripts
          skript_repo_ref: dev/patch
          extra_plugins_directory: extra-plugins/
