name: Spigot 1.16.5 and Skript 2.6.4-2.8.7

on:
  - push
  - pull_request

jobs:
  v1_16_5:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Lusk and run test scripts
        run: ./gradlew clean luskTest_1_16_5_spigot
      - name: Upload Nightly Build
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: lusk-nightly.jar
          path: build/libs/*
  v1_16_5_Skript-2_6_4-2_7_3-2_8_7:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v4
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Skript and run test scripts
        run: ./gradlew clean luskTestSkript_Spigot
      - name: Upload Nightly Build
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: lusk-nightly.jar
          path: build/libs/*